server:
  port: 8023

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/

spring:
  application:
    name: gateway-route
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: to_gateway_ha
          uri: lb://gateway-ha
          predicates:
            - Path=/ha/*
          filters:
            - StripPrefix=1
            - AddResponseHeader=hello, world
        - id: to_gateway_hi
          uri: lb://gateway-hi
          predicates:
            - Path=/hi/*
          filters:
            - StripPrefix=1
            - AddRequestHeader=hello, world