server:
  port: 8096

spring:
  application:
    name: service-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/

zuul:
  routes:
    api-a:
      serviceId: ribbon-ha
      path: /api-a/**
    api-b:
      serviceId: ribbon-hi
      path: /api-b/**
    feign-ha:
      path: /api-c/**
    feign-hi:
      path: /api-d/**
