server:
  port: 8096

spring:
  application:
    name: service-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: ribbon-ha
    api-b:
      path: /api-b/**
      serviceId: ribbon-hi
    api-c:
      path: /api-c/**
      serviceId: feign-ha
    api-d:
      path: /api-d/**
      serviceId: feign-hi
