server:
  port: 8071

spring:
  application:
    name: zipkin-ha
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/

feign:
  hystrix:
    enabled: true