##########################单注册中心##########################
spring:
  application:
    name: eureka-server

server:
  port: 8088

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

##########################多注册中心##########################
#spring:
#  profiles:
#    active: peer3

#---
#spring:
#  profiles: peer1
#  application:
#    name: eureka-server
#
#server:
#  port: 8088
#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8089/eureka/,http://localhost:8090/eureka/
#---
#spring:
#  profiles: peer2
#  application:
#    name: eureka-server
#
#server:
#  port: 8089
#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8088/eureka/,http://localhost:8090/eureka/
#---
#spring:
#  profiles: peer3
#  application:
#    name: eureka-server
#
#server:
#  port: 8090
#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8088/eureka/,http://localhost:8089/eureka/