server:
  port: 8025

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/

spring:
  application:
    name: gateway-predicate
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        #Path ==> curl localhost:8025/hello?name=123
#        - id: path_route
#          uri: lb://gateway-ha
#          predicates:
#            - Path=/hello
        #Method ==> get(curl localhost:8025/hello?name=123); post(curl -X POST localhost:8025/post)
#        - id: method_route
#          uri: http://localhost:8021
#          predicates:
#            - Method=POST
        #Time ==> curl localhost:8025/time
#        - id: time_route
#          uri: lb://gateway-ha
#          predicates:
#            - After=2020-10-30T15:00:22.432+08:00[Asia/Shanghai] #在该时区后发生
#            - Before=2020-10-30T16:00:22.432+08:00[Asia/Shanghai] #在该时区前发生
#            - Between=2020-10-30T15:00:22.432+08:00[Asia/Shanghai],2020-10-30T16:00:22.432+08:00[Asia/Shanghai] #在两个时区内发生
        #Header ==> curl -H id:1 localhost:8025/header  ||  curl localhost:8025/header -H "id:1"
#        - id: header_route
#          uri: lb://gateway-ha
#          predicates:
#            - Header=id,001 #携带header信息，相当于键值对，id为key，001为value
#            - Header=id,\d+ #携带header信息，相当于键值对，id为key，\d+为value，是一个正则表达式，表达为正数
        #Cookie ==> curl -H Cookie:username=yzm localhost:8025/cookie || curl localhost:8025/cookie --cookie "username=yzm"
#        - id: cookie_route
#          uri: lb://gateway-ha
#          predicates:
#            - Cookie=username,yzm #携带cookies信息，相当于键值对，username为key，yzm为value
#            - Cookie=username,\d+ #携带cookies信息，相当于键值对，username为key，\d+为value
        #Host ==> curl -H Host:a.another.com localhost:8025/host || curl localhost:8025/host -H "host:a.another.com"
#        - id: host_route
#          uri: lb://gateway-ha
#          predicates:
#            - Host=**.baidu.com,**.another.com
        #Query ==> curl localhost:8025/query?number=123
        - id: query_route
          uri: lb://gateway-ha
          predicates:
            - Query=number,123 #带查询条件，第一个是查询参数，第二个是可选的值，有参数名为number且值=123
#            - Query=number #带查询条件，有参数名为number，值无所谓
#            - Query=number,\d+